Updated uperf workflow
arcalot/arcaflow-workflows pull request #20
Opened 2023-11-07 18:09 UTC by jaredoconnell

Now uses stop-if, as well as the workflow v0.2.0 format

This will be a draft until someone can confirm that it works. I'm having trouble with the service step in my setup.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2023-11-15 19:41 UTC, jaredoconnell commented
This is ready for review. It seems to occasionally fail, but I doubt that's because of the recent changes. It's possible that there's not enough delays or ready-checks as-designed. Especially related to the service.

2023-11-16 12:48 UTC, dustinblack requested changes
I've noted a number of plugin version tags that should probably be updated. I will also try to find the time to functionally test this.

2023-11-16 12:48 UTC, dustinblack commented on network-performance/network-streaming-performance-k8s/workflow.yaml
> +      src: quay.io/arcalot/arcaflow-plugin-utilities:0.2.0
Bump this to 0.4.0

2023-11-16 12:48 UTC, dustinblack commented on network-performance/network-streaming-performance-k8s/workflow.yaml
> +      src: quay.io/arcalot/arcaflow-plugin-kubeconfig:0.2.0
Bump this to 0.3.1

2023-11-16 12:48 UTC, dustinblack commented on network-performance/network-streaming-performance-k8s/workflow.yaml
> +      src: quay.io/arcalot/arcaflow-plugin-metadata:0.1.0
Bump this to 0.4.0

2023-11-16 23:12 UTC, jaredoconnell commented
Versions bumped. Untested.

2024-02-08 13:28 UTC, dustinblack commented
In functional testing on a kind cluster, something is keeping the uperf plugin from accessing the service:
```
2024-02-08T14:25:03+01:00	error	source=workflow	Output ID for step "uperf_client" is "error".
Output data: "map[error:Failed to parse output: could not find profile name.
Output: Error getting SSL CTX:1
Allocating shared memory of size 156624 bytes
Error connecting to arcaflow-svc-plugin-wzlzd

** TCP: Cannot connect to arcaflow-svc-plugin-wzlzd:20000 Connection refused
]"
```

Still looking into this.

2024-03-01 13:23 UTC, dustinblack approved these changes

2024-03-01 13:23 UTC, merged